# Generated by Django 4.0.7 on 2022-10-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staffUser',
        ),
    ]
