# Generated by Django 4.0.7 on 2022-09-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200, null=True)),
                ('otherNames', models.CharField(max_length=250, null=True)),
                ('DateOfBirth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('academicBg', models.CharField(max_length=200)),
                ('skills', models.TextField(max_length=250)),
                ('IntAreaOfPlacement', models.CharField(max_length=100)),
                ('DurOfPLacement', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=50)),
                ('comments', models.TextField(max_length=200)),
            ],
        ),
    ]
