# Generated by Django 4.0.7 on 2022-10-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='citizenship',
        ),
        migrations.AddField(
            model_name='donor',
            name='country',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
    ]
