# Generated by Django 4.0.7 on 2022-09-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorname', models.CharField(max_length=200)),
                ('dphonenumber', models.IntegerField(null=True)),
                ('dMeansofGiving', models.CharField(max_length=120)),
                ('dFReqOfGiving', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=100)),
                ('TCountryOfBirth', models.CharField(max_length=100)),
                ('TGender', models.CharField(max_length=10)),
                ('Tnationality', models.CharField(max_length=100)),
                ('TPassportNmber', models.IntegerField(null=True)),
                ('TPermResAddress', models.TextField(blank=True, null=True)),
                ('TEmailAddress', models.EmailField(max_length=254)),
                ('TEmergContact', models.IntegerField(null=True)),
                ('TNameOfInstOrOcc', models.CharField(max_length=200)),
            ],
        ),
    ]
