# Generated by Django 4.0.7 on 2022-10-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_volunteer_citizenship_donor_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
