# Generated by Django 4.0.7 on 2022-10-18 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_dfreqofgiving_donor_freqofgiving_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='otherNames',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='surname',
        ),
        migrations.AddField(
            model_name='donor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='EmailAddress',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='comments',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
