# Generated by Django 4.0.7 on 2022-10-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_donor_options_alter_tour_id_alter_volunteer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-date']},
        ),
    ]
