# Generated by Django 4.0.7 on 2022-11-04 10:18

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_tour_options_alter_volunteer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='tour',
            name='CountryOfBirth',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phoneNumber',
            field=models.TextField(null=True),
        ),
    ]
