# Generated by Django 4.0.7 on 2022-11-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_donor_country_alter_tour_countryofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tour',
            name='CountryOfBirth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
