# Generated by Django 4.0.7 on 2022-11-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_donor_country_alter_tour_countryofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='PhoneNumber',
            field=models.TextField(null=True),
        ),
    ]
