# Generated by Django 4.0.7 on 2023-01-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_volunteer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='DurOfPLacement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='IntAreaOfPlacement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='academicBg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='comments',
            field=models.TextField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
