# Generated by Django 4.0.7 on 2023-01-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_volunteer_dateofbirth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='PhoneNumber',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='DateOfBirth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='DurOfPLacement',
            new_name='durOfPlacement',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='IntAreaOfPlacement',
            new_name='firstName',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='FReqOfGiving',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='MeansofGiving',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='firstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='lastName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='phoneNumber',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='addInfo',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='intAreaOfPlacement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phoneNumber',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
