# Generated by Django 4.0.7 on 2023-01-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_tour_rename_phonenumber_donor_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='firstName',
        ),
    ]
