# Generated by Django 4.0.7 on 2023-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_volunteer_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='fullName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
