# Generated by Django 4.0.7 on 2023-01-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_volunteer_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
