# Generated by Django 4.0.7 on 2023-01-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_donor_email_alter_donor_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
