# Generated by Django 4.0.7 on 2023-01-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_volunteer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phoneNumber',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
