# Generated by Django 4.0.7 on 2023-02-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_pagehit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='message',
        ),
        migrations.AddField(
            model_name='donor',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='ref',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
