# Generated by Django 4.0.7 on 2023-02-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_profile_groups_alter_profile_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/images/avatars'),
        ),
    ]
